// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const DeleteMessage = `-- name: DeleteMessage :exec
DELETE FROM messages
WHERE id = $1 AND sender_id = $2
`

type DeleteMessageParams struct {
	ID       pgtype.UUID `json:"id"`
	SenderID pgtype.UUID `json:"sender_id"`
}

func (q *Queries) DeleteMessage(ctx context.Context, arg DeleteMessageParams) error {
	_, err := q.db.Exec(ctx, DeleteMessage, arg.ID, arg.SenderID)
	return err
}

const EditMessage = `-- name: EditMessage :one
UPDATE messages
SET content = $1, is_edited = TRUE, edited_at = NOW()
WHERE id = $2 AND sender_id = $3
RETURNING id, room_id, sender_id, content, reply_to_id, is_edited, edited_at, created_at
`

type EditMessageParams struct {
	Content  string      `json:"content"`
	ID       pgtype.UUID `json:"id"`
	SenderID pgtype.UUID `json:"sender_id"`
}

func (q *Queries) EditMessage(ctx context.Context, arg EditMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, EditMessage, arg.Content, arg.ID, arg.SenderID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.SenderID,
		&i.Content,
		&i.ReplyToID,
		&i.IsEdited,
		&i.EditedAt,
		&i.CreatedAt,
	)
	return i, err
}

const GetMessageByID = `-- name: GetMessageByID :one
SELECT id, room_id, sender_id, content, reply_to_id, is_edited, edited_at, created_at
FROM messages
WHERE id = $1
`

func (q *Queries) GetMessageByID(ctx context.Context, id pgtype.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, GetMessageByID, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.SenderID,
		&i.Content,
		&i.ReplyToID,
		&i.IsEdited,
		&i.EditedAt,
		&i.CreatedAt,
	)
	return i, err
}

const GetRoomMessages = `-- name: GetRoomMessages :many
SELECT m.id, m.room_id, m.sender_id, u.username AS sender_name, m.content, m.reply_to_id, m.is_edited, m.edited_at, m.created_at
FROM messages m
JOIN users u ON m.sender_id = u.id
WHERE m.room_id = $1
ORDER BY m.created_at ASC
LIMIT $2 OFFSET $3
`

type GetRoomMessagesParams struct {
	RoomID pgtype.UUID `json:"room_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type GetRoomMessagesRow struct {
	ID         pgtype.UUID        `json:"id"`
	RoomID     pgtype.UUID        `json:"room_id"`
	SenderID   pgtype.UUID        `json:"sender_id"`
	SenderName string             `json:"sender_name"`
	Content    string             `json:"content"`
	ReplyToID  pgtype.UUID        `json:"reply_to_id"`
	IsEdited   pgtype.Bool        `json:"is_edited"`
	EditedAt   pgtype.Timestamptz `json:"edited_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetRoomMessages(ctx context.Context, arg GetRoomMessagesParams) ([]GetRoomMessagesRow, error) {
	rows, err := q.db.Query(ctx, GetRoomMessages, arg.RoomID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRoomMessagesRow
	for rows.Next() {
		var i GetRoomMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.SenderID,
			&i.SenderName,
			&i.Content,
			&i.ReplyToID,
			&i.IsEdited,
			&i.EditedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SendMessage = `-- name: SendMessage :one
INSERT INTO messages (room_id, sender_id, content, reply_to_id)
VALUES ($1, $2, $3, $4)
RETURNING id, room_id, sender_id, content, reply_to_id, is_edited, edited_at, created_at
`

type SendMessageParams struct {
	RoomID    pgtype.UUID `json:"room_id"`
	SenderID  pgtype.UUID `json:"sender_id"`
	Content   string      `json:"content"`
	ReplyToID pgtype.UUID `json:"reply_to_id"`
}

func (q *Queries) SendMessage(ctx context.Context, arg SendMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, SendMessage,
		arg.RoomID,
		arg.SenderID,
		arg.Content,
		arg.ReplyToID,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.SenderID,
		&i.Content,
		&i.ReplyToID,
		&i.IsEdited,
		&i.EditedAt,
		&i.CreatedAt,
	)
	return i, err
}
