// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Message struct {
	ID        pgtype.UUID        `json:"id"`
	RoomID    pgtype.UUID        `json:"room_id"`
	SenderID  pgtype.UUID        `json:"sender_id"`
	Content   string             `json:"content"`
	ReplyToID pgtype.UUID        `json:"reply_to_id"`
	IsEdited  pgtype.Bool        `json:"is_edited"`
	EditedAt  pgtype.Timestamptz `json:"edited_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	IsRevoked pgtype.Bool        `json:"is_revoked"`
}

type Room struct {
	ID        pgtype.UUID        `json:"id"`
	Name      pgtype.Text        `json:"name"`
	IsGroup   pgtype.Bool        `json:"is_group"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RoomParticipant struct {
	RoomID   pgtype.UUID        `json:"room_id"`
	UserID   pgtype.UUID        `json:"user_id"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

type User struct {
	ID           pgtype.UUID `json:"id"`
	Username     string      `json:"username"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	// 0=offline, 1=online, 2=idle, 3=invisible
	Status    pgtype.Int2        `json:"status"`
	LastSeen  pgtype.Timestamptz `json:"last_seen"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
