// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rooms.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const AddRoomParticipant = `-- name: AddRoomParticipant :exec
INSERT INTO room_participants (room_id, user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddRoomParticipantParams struct {
	RoomID pgtype.UUID `json:"room_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) AddRoomParticipant(ctx context.Context, arg AddRoomParticipantParams) error {
	_, err := q.db.Exec(ctx, AddRoomParticipant, arg.RoomID, arg.UserID)
	return err
}

const CreateRoom = `-- name: CreateRoom :one
INSERT INTO rooms (name, is_group, created_by)
VALUES ($1, $2, $3)
RETURNING id, name, is_group, created_by, created_at
`

type CreateRoomParams struct {
	Name      pgtype.Text `json:"name"`
	IsGroup   pgtype.Bool `json:"is_group"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, CreateRoom, arg.Name, arg.IsGroup, arg.CreatedBy)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsGroup,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const GetRoomByID = `-- name: GetRoomByID :one
SELECT id, name, is_group, created_by, created_at
FROM rooms
WHERE id = $1
`

func (q *Queries) GetRoomByID(ctx context.Context, id pgtype.UUID) (Room, error) {
	row := q.db.QueryRow(ctx, GetRoomByID, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsGroup,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const GetRoomParticipants = `-- name: GetRoomParticipants :many
SELECT u.id, u.username, u.email, u.status, u.last_seen, us.color, rp.joined_at
FROM room_participants rp
JOIN users u ON rp.user_id = u.id
LEFT JOIN user_settings us ON us.user_id = u.id
WHERE rp.room_id = $1
`

type GetRoomParticipantsRow struct {
	ID       pgtype.UUID        `json:"id"`
	Username string             `json:"username"`
	Email    string             `json:"email"`
	Status   pgtype.Int2        `json:"status"`
	LastSeen pgtype.Timestamptz `json:"last_seen"`
	Color    pgtype.Text        `json:"color"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

func (q *Queries) GetRoomParticipants(ctx context.Context, roomID pgtype.UUID) ([]GetRoomParticipantsRow, error) {
	rows, err := q.db.Query(ctx, GetRoomParticipants, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRoomParticipantsRow
	for rows.Next() {
		var i GetRoomParticipantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Status,
			&i.LastSeen,
			&i.Color,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const IsParticipant = `-- name: IsParticipant :one
SELECT EXISTS (
    SELECT 1 FROM room_participants
    WHERE room_id = $1 AND user_id = $2
)
`

type IsParticipantParams struct {
	RoomID pgtype.UUID `json:"room_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) IsParticipant(ctx context.Context, arg IsParticipantParams) (bool, error) {
	row := q.db.QueryRow(ctx, IsParticipant, arg.RoomID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const RemoveRoomParticipant = `-- name: RemoveRoomParticipant :exec
DELETE FROM room_participants
WHERE room_id = $1 AND user_id = $2
`

type RemoveRoomParticipantParams struct {
	RoomID pgtype.UUID `json:"room_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) RemoveRoomParticipant(ctx context.Context, arg RemoveRoomParticipantParams) error {
	_, err := q.db.Exec(ctx, RemoveRoomParticipant, arg.RoomID, arg.UserID)
	return err
}
