// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CreateUserSettings = `-- name: CreateUserSettings :one
INSERT INTO user_settings (user_id, color)
VALUES ($1, $2)
RETURNING user_id, color, language, notifications_enabled, updated_at
`

type CreateUserSettingsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Color  string      `json:"color"`
}

func (q *Queries) CreateUserSettings(ctx context.Context, arg CreateUserSettingsParams) (UserSetting, error) {
	row := q.db.QueryRow(ctx, CreateUserSettings, arg.UserID, arg.Color)
	var i UserSetting
	err := row.Scan(
		&i.UserID,
		&i.Color,
		&i.Language,
		&i.NotificationsEnabled,
		&i.UpdatedAt,
	)
	return i, err
}

const GetUserSettings = `-- name: GetUserSettings :one
SELECT user_id, color, language, notifications_enabled, updated_at FROM user_settings
WHERE user_id = $1
`

func (q *Queries) GetUserSettings(ctx context.Context, userID pgtype.UUID) (UserSetting, error) {
	row := q.db.QueryRow(ctx, GetUserSettings, userID)
	var i UserSetting
	err := row.Scan(
		&i.UserID,
		&i.Color,
		&i.Language,
		&i.NotificationsEnabled,
		&i.UpdatedAt,
	)
	return i, err
}

const UpdateUserSettings = `-- name: UpdateUserSettings :one
UPDATE user_settings
SET color = COALESCE($2, color),
    language = COALESCE($3, language),
    notifications_enabled = COALESCE($4, notifications_enabled),
    updated_at = NOW()
WHERE user_id = $1
RETURNING user_id, color, language, notifications_enabled, updated_at
`

type UpdateUserSettingsParams struct {
	UserID               pgtype.UUID `json:"user_id"`
	Color                pgtype.Text `json:"color"`
	Language             pgtype.Text `json:"language"`
	NotificationsEnabled pgtype.Bool `json:"notifications_enabled"`
}

func (q *Queries) UpdateUserSettings(ctx context.Context, arg UpdateUserSettingsParams) (UserSetting, error) {
	row := q.db.QueryRow(ctx, UpdateUserSettings,
		arg.UserID,
		arg.Color,
		arg.Language,
		arg.NotificationsEnabled,
	)
	var i UserSetting
	err := row.Scan(
		&i.UserID,
		&i.Color,
		&i.Language,
		&i.NotificationsEnabled,
		&i.UpdatedAt,
	)
	return i, err
}
