// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const GetUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, status, last_seen, created_at, password_hash
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID           pgtype.UUID        `json:"id"`
	Username     string             `json:"username"`
	Email        string             `json:"email"`
	Status       pgtype.Int2        `json:"status"`
	LastSeen     pgtype.Timestamptz `json:"last_seen"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	PasswordHash string             `json:"password_hash"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, GetUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Status,
		&i.LastSeen,
		&i.CreatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const GetUserByID = `-- name: GetUserByID :one
SELECT id, username, email, status, last_seen, created_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID        pgtype.UUID        `json:"id"`
	Username  string             `json:"username"`
	Email     string             `json:"email"`
	Status    pgtype.Int2        `json:"status"`
	LastSeen  pgtype.Timestamptz `json:"last_seen"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, GetUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Status,
		&i.LastSeen,
		&i.CreatedAt,
	)
	return i, err
}

const GetUserRooms = `-- name: GetUserRooms :many
SELECT r.id, r.name, r.is_group, r.created_by, r.created_at
FROM rooms r
JOIN room_participants rp ON r.id = rp.room_id
WHERE rp.user_id = $1
ORDER BY r.created_at DESC
`

func (q *Queries) GetUserRooms(ctx context.Context, userID pgtype.UUID) ([]Room, error) {
	rows, err := q.db.Query(ctx, GetUserRooms, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsGroup,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const RegisterUser = `-- name: RegisterUser :one
INSERT INTO users (username, email, password_hash)
VALUES ($1, $2, $3)
RETURNING id, username, email, status, last_seen, created_at
`

type RegisterUserParams struct {
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

type RegisterUserRow struct {
	ID        pgtype.UUID        `json:"id"`
	Username  string             `json:"username"`
	Email     string             `json:"email"`
	Status    pgtype.Int2        `json:"status"`
	LastSeen  pgtype.Timestamptz `json:"last_seen"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) RegisterUser(ctx context.Context, arg RegisterUserParams) (RegisterUserRow, error) {
	row := q.db.QueryRow(ctx, RegisterUser, arg.Username, arg.Email, arg.PasswordHash)
	var i RegisterUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Status,
		&i.LastSeen,
		&i.CreatedAt,
	)
	return i, err
}

const RegisterUserWithSettings = `-- name: RegisterUserWithSettings :one
WITH new_user AS (
    INSERT INTO users (username, email, password_hash)
    VALUES ($1, $2, $3)
    RETURNING id, username, email, password_hash, status, last_seen, created_at
),
settings_insert AS (
    INSERT INTO user_settings (user_id, color)
    SELECT id, $4 FROM new_user
)
SELECT id, username, email, status, last_seen, created_at FROM new_user
`

type RegisterUserWithSettingsParams struct {
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Color        string `json:"color"`
}

type RegisterUserWithSettingsRow struct {
	ID        pgtype.UUID        `json:"id"`
	Username  string             `json:"username"`
	Email     string             `json:"email"`
	Status    pgtype.Int2        `json:"status"`
	LastSeen  pgtype.Timestamptz `json:"last_seen"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) RegisterUserWithSettings(ctx context.Context, arg RegisterUserWithSettingsParams) (RegisterUserWithSettingsRow, error) {
	row := q.db.QueryRow(ctx, RegisterUserWithSettings,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Color,
	)
	var i RegisterUserWithSettingsRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Status,
		&i.LastSeen,
		&i.CreatedAt,
	)
	return i, err
}

const SearchUsers = `-- name: SearchUsers :many
SELECT u.id, u.username, u.email, u.status, u.last_seen, u.created_at, s.color
FROM users u
LEFT JOIN user_settings s ON s.user_id = u.id
WHERE (
    u.username ILIKE '%' || $1 || '%'
    OR u.email = $1
    OR u.id::text = $1
)
AND u.id <> $2
ORDER BY u.username
LIMIT $3
`

type SearchUsersParams struct {
	SearchQuery   pgtype.Text `json:"search_query"`
	ExcludeUserID pgtype.UUID `json:"exclude_user_id"`
	ResultLimit   int32       `json:"result_limit"`
}

type SearchUsersRow struct {
	ID        pgtype.UUID        `json:"id"`
	Username  string             `json:"username"`
	Email     string             `json:"email"`
	Status    pgtype.Int2        `json:"status"`
	LastSeen  pgtype.Timestamptz `json:"last_seen"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Color     pgtype.Text        `json:"color"`
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error) {
	rows, err := q.db.Query(ctx, SearchUsers, arg.SearchQuery, arg.ExcludeUserID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchUsersRow
	for rows.Next() {
		var i SearchUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Status,
			&i.LastSeen,
			&i.CreatedAt,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
