// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const GetUserByID = `-- name: GetUserByID :one
SELECT id, username, email, status, last_seen, created_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID        pgtype.UUID        `json:"id"`
	Username  string             `json:"username"`
	Email     string             `json:"email"`
	Status    pgtype.Int2        `json:"status"`
	LastSeen  pgtype.Timestamptz `json:"last_seen"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, GetUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Status,
		&i.LastSeen,
		&i.CreatedAt,
	)
	return i, err
}

const GetUserRooms = `-- name: GetUserRooms :many
SELECT r.id, r.name, r.is_group, r.created_by, r.created_at
FROM rooms r
JOIN room_participants rp ON r.id = rp.room_id
WHERE rp.user_id = $1
ORDER BY r.created_at DESC
`

func (q *Queries) GetUserRooms(ctx context.Context, userID pgtype.UUID) ([]Room, error) {
	rows, err := q.db.Query(ctx, GetUserRooms, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsGroup,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const RegisterUser = `-- name: RegisterUser :one
INSERT INTO users (username, email, password_hash)
VALUES ($1, $2, $3)
RETURNING id, username, email, status, last_seen, created_at
`

type RegisterUserParams struct {
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

type RegisterUserRow struct {
	ID        pgtype.UUID        `json:"id"`
	Username  string             `json:"username"`
	Email     string             `json:"email"`
	Status    pgtype.Int2        `json:"status"`
	LastSeen  pgtype.Timestamptz `json:"last_seen"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) RegisterUser(ctx context.Context, arg RegisterUserParams) (RegisterUserRow, error) {
	row := q.db.QueryRow(ctx, RegisterUser, arg.Username, arg.Email, arg.PasswordHash)
	var i RegisterUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Status,
		&i.LastSeen,
		&i.CreatedAt,
	)
	return i, err
}
